### ISSUE TITLE
Hide "Who to follow" and "Promoted tweet" sections in profile pages

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#10]
Just noticed "Who to follow" is always three tweets down in the primary column instead of being in the sidebar when viewing someone's profile.

There's also a similarly styled "Promoted tweet" section now (or maybe it was always there - uBlock Origin was hiding it)

**Comment by insin** [comment]
"Who to follow" in the timeline can mostly be hidden with CSS, with a couple of DOM manipulations needed to remove the space left behind.

Before:
![firefox_pyd041Fyo5](https://user-images.githubusercontent.com/226692/63344148-11ef1200-c393-11e9-99b4-5c0f181633fc.png)

```css
/* "Who to follow" heading */
div[aria-label="Timeline: Your Home Timeline"] h2[role="heading"],
/* Who to follow users */
div[data-testid="UserCell"],
/* "Show more" link */
a[href="/who_to_follow"] {
  display: none;
}

/* White space above: div containing the h2 */
/* Grey space below: the div following the "Show more" link */
```

After:
![firefox_msX2jGRdkN](https://user-images.githubusercontent.com/226692/63344174-23d0b500-c393-11e9-8bc4-073a894b96ba.png)

DOM to be manipulated:
![firefox_SEEWEdSyax](https://user-images.githubusercontent.com/226692/63344301-76aa6c80-c393-11e9-8bc8-681411eeff49.png)
