### ISSUE TITLE
Option to hide blue ticks now they don't mean anything?

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#146]
WIP if people want it:

```css
/* Timeline names */
div[data-testid="User-Names"] > div > div > a > div > div + div,
/* Timeline QTs */
div[data-testid^="UserAvatar-Container"] + div + div,
/* Profile heading (desktop) */
body.Profile div[data-testid="primaryColumn"] h2 span + span,
/* Profile name */
body.Profile div[data-testid="UserName"] div[dir="auto"] > span + span {
  display: none;
}
```
