### ISSUE TITLE
Re-style "Latest Tweets" and "Retweets" to match styling for tabs on other parts of the site

### ISSUE THREAD

**Issue by TheAntiFanboy** [insin/tweak-new-twitter#152]
Right now, the styling for Latest Tweets and Retweets is a bit unconventional.

![Current design](https://i.imgur.com/fSDvlp6.png)

- Using header styling to represent what are effectively clickable tabs is somewhat confusing, and makes it less obvious that these are interactive.
- Latest Tweets is the active tab, so coloring it blue is odd, since blue text usually means "clickable link " and black text means "non-interactive".
- Having Latest Tweets left-aligned and Retweets right-aligned does not make it obvious that they're different sections.

My suggestion would be to mimic tab styling on other parts of the site, like so:

![Suggested design](https://i.imgur.com/7eVkNEw.png)

Center the tab text, give it subheader font styling, make Active Tab text black and Inactive Tab text gray, and (if possible) add the blue half-width underline.

**Comment by insin** [comment]
This should be doable. quick proof of concept on the main parts done in F12 developer tools:

![firefox_71VCjENAG1](https://user-images.githubusercontent.com/226692/201410059-0d9154e3-8f75-4805-9416-e86e75b4a321.gif)

Just leaving some notes for myself:

```css
/*
Markup changes needed:
- Maked the cloned Retweets header a sibling of the timeline title
- Add .tnt_tabs to their shared parent
- Add an empty <div> after h2 > span
*/
.tnt_tabs {
  display: flex;
  flex-direction: row;
}
.tnt_tabs > div {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}
.tnt_tabs > div:hover {
  background: rgba(15, 20, 25, 0.1);
}
.tnt_tabs > div > h2 {
  position: relative;
  height: 100%;
  display: flex; 
  align-items: center;
  justify-content: center;
  font-size: 15px;
  line-height: 20px;
  font-weight: normal;
  color: rgb(15, 20, 25) !important;
}
.tnt_tabs > div > h2 > div {
  position: absolute;
  bottom: 0;
  height: 0;
  background-color: rgb(29, 155, 240);
  width: 100%;
  min-width: 56px;
}
body.LatestTweets main h2:not(#tnt_separated_tweets),
body.SeparatedTweets #tnt_separated_tweets {
  font-weight: bold;
}
body.LatestTweets .tnt_tabs > div > h2:not(#tnt_separated_tweets) > div,
body.SeparatedTweets .tnt_tabs > div > #tnt_separated_tweets > div {
  height: 4px;
}
```
