### ISSUE TITLE
Dropdown menu items are now all bold

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#156]
I don't know if this is intended, as it looks so bad:

![firefox_zbS1xS1mpE](https://user-images.githubusercontent.com/226692/203585453-9ffe8a32-766b-4f29-8070-c4c3e0aa310b.png)

If it was intended, we can add a new default-enabled option which does this:

```css
[data-testid="Dropdown"] [role="menuitem"] [dir="auto"] {
  font-weight: normal;
}
```

![firefox_jI8dZGxTVm](https://user-images.githubusercontent.com/226692/203585473-bf059eeb-6836-4f27-973a-77e4eb7211f3.png)
