### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by gesdemirei** [insin/tweak-new-twitter#39]
Would you add hide option for “Translate Tweet” and “Like Quote Tweets Retweets” line on next updates?

**Comment by insin** [comment]
How would you describe not having the under-tweet stuff as a feature? Low interaction mode, perhaps?

It looks pretty nice. Parking this CSS here for later use.

```css
[data-testid="tweet"] [role="group"],
body.Tweet [data-testid="tweet"] + div > [role="group"],
body.Tweet [data-testid="tweet"] + div > div:nth-last-of-type(2) {
  display: none;
}
```

![firefox_wHwH3yYjoI](https://user-images.githubusercontent.com/226692/126825526-518d47d9-f768-4ff1-a958-d17ef8a28f1d.png)

![O86emAxaxf](https://user-images.githubusercontent.com/226692/126825552-54d3dcc8-d4cb-45ac-a975-e07e1773f701.png)
