### ISSUE TITLE
Hiding the account switcher hides the only way to log out

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#44]
As reported here:

https://twitter.com/josephfelldown/status/1414361564975706119

> Discovered that the "Tweak New Twitter" extension I use to make this awful place more bearable removes the log out button, which is ironic.

This would reduce it to just the menu ellipsis instead:
```css
header[role="banner"] > div > div > div > div:last-child {
  flex-shrink: 1 !important;
  align-items: end !important;
}
[data-testid="SideNav_AccountSwitcher_Button"] > div:first-child,
[data-testid="SideNav_AccountSwitcher_Button"] > div:first-child + div {
  display: none;
}
```

![firefox_oPH8K5vrGe](https://user-images.githubusercontent.com/226692/125237958-dadccd80-e329-11eb-93bf-5767281ab6f8.png)

Should we still offer the option to completely hide it, or just make this what the "Hide account switcher (in footer)" setting does?
