### ISSUE TITLE
Hide images in timeline tweets by default, click to view

### ISSUE THREAD

**Issue by insin** [insin/tweak-new-twitter#5]
For a low-noise timeline with more text, fewer images.

With New Twitter, you no longer move off the timeline and lose your place if you click on an image (unless it decides it's time to randomly load more tweets, like it does).

- [x] Single images
- [ ] 2-4 images
- [ ] GIFs
- [ ] Other video (if not handled the same way as GIFs)
- [ ] Images/video in metadata from a linked URL

[Stylus](https://github.com/openstyles/stylus#readme) is a non-spying-on you fork of the Stylish extension which is handy for tinkering with a site's CSS in a persistent manner.

**Comment by insin** [comment]
Progress:

```css
/* Hide images added to tweets */
div[data-testid="tweet"] a[href$="/photo/1"], 
div[data-testid="tweet"] a[href$="/photo/2"],
div[data-testid="tweet"] a[href$="/photo/3"],
div[data-testid="tweet"] a[href$="/photo/4"] {
  text-decoration: none;
  color: rgb(231, 231, 231);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", 
               Roboto, Ubuntu, "Helvetica Neue", sans-serif;
  font-size: 15px;
}
div[data-testid="tweet"] a[href$="/photo/1"]::before, 
div[data-testid="tweet"] a[href$="/photo/2"]::before,
div[data-testid="tweet"] a[href$="/photo/3"]::before,
div[data-testid="tweet"] a[href$="/photo/4"]::before {
  content: attr(href);
  display: block;
  padding: 3px 0;
  text-align: center;
}
div[data-testid="tweet"] a[href$="/photo/1"] div[style^="padding-bottom"], 
div[data-testid="tweet"] a[href$="/photo/2"] div[style^="padding-bottom"],
div[data-testid="tweet"] a[href$="/photo/3"] div[style^="padding-bottom"],
div[data-testid="tweet"] a[href$="/photo/4"] div[style^="padding-bottom"] {
  padding-bottom: 0 !important;
}
```

We can observe the `night_mode` cookie and rewrite the CSS to tweak the font colour when it changes:

```js
let color = /night_mode=(\d)/.exec(document.cookie)[1] == '1'
  ? 'rgb(231, 231 ,231)' 
  : 'rgb(0, 0, 0)'
```

This works great for single images:

![image](https://user-images.githubusercontent.com/226692/61834999-618a0d00-aebd-11e9-8466-7cce0c297371.png)

Multiple images, not so much:

![firefox_wOW8iwrKc1](https://user-images.githubusercontent.com/226692/61835241-41a71900-aebe-11e9-8dde-257469294250.png)

**Comment by insin** [comment]
This seems to get rid of most media, except for tweets which have no text, just a GIF. There may also be a false positive with the `::before content` on polls.

`div[data-testid="tweet"] div[dir="auto"][lang] + div` gets you the tree immediately after a tweet's text, which is where the media lives.

```css
/* Replacement content for the media we're about to hide. */
div[data-testid="tweet"] div[dir="auto"][lang] + div > div > div::before {
  text-decoration: none;
  color: rgb(231, 231, 231);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", 
               Roboto, Ubuntu, "Helvetica Neue", sans-serif;
  font-size: 15px;
  content: "Click to view image 📷";
  display: block;
  text-align: center;
}

/* Remove the padding which gives media their height */
div[data-testid="tweet"] div[dir="auto"][lang] + div div[style^="padding-bottom"] {
  padding-bottom: 0 !important;
}

/* Hide play video icon */
div[data-testid="tweet"] div[dir="auto"][lang] + div div[style^="width: calc"] {
    display: none;
}
```

**Comment by insin** [comment]
This is hiding everything in my timeline, with the false positive on polls still present - there's just nothing to check above the poll items in the tree.

```css
/* Replacement content for the media we're about to hide. */
div[data-testid="tweet"] > div:nth-child(2) > div:first-child > div:not([dir]):not([lang]):last-child > div > div:first-child::before {
  text-decoration: none;
  color: rgb(231, 231, 231);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", 
               Roboto, Ubuntu, "Helvetica Neue", sans-serif;
  font-size: 15px;
  content: "Click to view image 📷";
  display: block;
  text-align: center;
  /* Vertically centre when replacing video play buttons */
  align-self: center;
}

/* Remove the padding which gives media their height */
div[data-testid="tweet"] > div:nth-child(2) > div:first-child > div:not([dir]):not([lang]):last-child div[style^="padding-bottom"] {
  padding-bottom: 0 !important;
}

/* Hide video play buttons */
div[data-testid="tweet"] > div:nth-child(2) > div:first-child > div:not([dir]):not([lang]):last-child div[style^="width: calc"] {
    display: none;
}
```

Debug rules for when this inevitably breaks:
```css
/* Media container after tweet content */
div[data-testid="tweet"] > div:nth-child(2) > div:first-child > div:not([dir]):not([lang]):last-child {
    outline: 1px solid red;
}
/* Element which actually contains the media (there can be another sibling with metadata) */
div[data-testid="tweet"] > div:nth-child(2) > div:first-child > div:not([dir]):not([lang]):last-child > div > div:first-child {
    outline: 1px solid hotpink;
}
```
